name: setup-build-env
description: Setup common build environment (checkout, toolchain, build cache)

inputs:
  toolchain:
    description: "defines the toolchain to be installed"
    required: false
    default: stable
  components:
    description: "default additional components to be installed"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        profile: minimal
        override: true

    - name: Add problem matchers
      shell: bash
      run: echo "::add-matcher::setup-build-env/rust.json"

    - name: Cache
      uses: Swatinem/rust-cache@v1
