name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: nickelc/actions/setup-build-env@master
        with:
          toolchain: nightly

      - run: cargo new self-test
      - run: echo "fn unused() {}" >> self-test/src/main.rs
      - run: cargo build --manifest-path self-test/Cargo.toml
